#pragma once

#ifndef CONSOLE_EXT_VERSION_HPP
#define CONSOLE_EXT_VERSION_HPP

#define CONSOLE_EXT_MAJOR_VERSION		0
#define CONSOLE_EXT_MINOR_VERSION		2
#define CONSOLE_EXT_PATCH_VERSION		2
#define CONSOLE_EXT_BUILD_NUMBER		30
#define CONSOLE_EXT_BUILD_TYPE			"alpha"
#define CONSOLE_EXT_REVISION_NUMBER		0

#endif // !CONSOLE_EXT_VERSION_HPP